# Generated by Django 6.0.1 on 2026-01-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_ai",
        ),
        migrations.AddField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("USER", "User"), ("AI", "AI")], default="user", max_length=10
            ),
        ),
    ]
